#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr

cmdr create cmdline cmdline {

    private scissors {
	state  s XXX {}
	option o YYY {}
	input  a AAA { }
	input  b BBB { optional }
	input  c CCC { list }
    } ::cut
    officer hammer {
	private nail  {} ::drive
	private screw {} ::drive
    }
    default hammer
}

cmdline do
exit
