#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr

cmdr create cmdline cmdline {

    private scissors {
	state  state  XXX
	option option YYY
	option debug DDD { undocumented }
	input  alpha  AAA
	input  beta   BBB { optional }
	input  gamma  CCC { list }
    } ::cut
}

[cmdline lookup scissors] interact
exit
