#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

cmdr say operation {Upload } {
    after 5000 {set ::done ok}
    vwait ::done
} -every 50 -play {cmdr say turn}

exit
