#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

# infinite slider - semi-barberpole
set B [cmdr say animate -phases {
    {[         ]}
    {[*        ]}
    {[**       ]}
    {[***      ]}
    {[* **     ]}
    {[ * **    ]}
    {[  * **   ]}
    {[   * **  ]}
    {[    * ** ]}
    {[     * **]}
    {[      * *]}
    {[       * ]}
    {[        *]}
}]
while {1} {
    after 100
    cmdr say rewind
    $B step
}

exit
