#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

# infinite slider - semi-barberpole
set B [cmdr say animate -phases [cmdr say slider-phases 9 ***]]
while {1} {
    after 100
    cmdr say rewind
    $B step
}

exit
