#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

# infinite barberpole with a prefix
set B [cmdr say barberpole -width 30]
cmdr say add "download ... "
cmdr say lock-prefix
while {1} {
    #
    # fake download, unknown size, sync ... actual use:
    # - fcopy callback,
    # - http progress-callback
    # - tcllib transfer callback
    after 100
    #
    cmdr say rewind
    $B step
}

exit
