#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

# infinite pulse - semi-barberpole
set B [cmdr say animate \
	   -phases [cmdr say pulse-phases 3 [cmdr color {bg-blue white} *]]]
while {1} {
    after 100
    cmdr say rewind
    $B step
}

exit
