#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

# percent progress bar
set B [cmdr say progress -max 1000 -width 50]
set C [cmdr say percent  -max 1000]
set i 0
cmdr say add "upload ... "
cmdr say lock-prefix
while {$i < 1000} {
    #
    # fake upload, sync ... actual use:
    # - fcopy callback,
    # - http progress-callback
    # - tcllib transfer callback
    after 10
    #
    cmdr say rewind
    incr i
    cmdr say add \[
    $B step $i
    cmdr say add \]

    cmdr say add { }
    $C step $i
}
#after 10
#cmdr say rewind
cmdr say line { OK}

exit
