#!/usr/bin/env tclsh
# -*- tcl -*-
package require Tcl 8.5
package require cmdr::say

# infinite barberpole
set B [cmdr say barberpole -width 30]
while {1} {
    after 100
    cmdr say rewind
    $B step
}

exit
