
[list_begin definitions]
[def cmdline]      Output of method [method cmdline].
[def code]         Output of method [method code].
[def default]      Output of method [method default].
[def defered]      Output of method [method defered].
[def description]  Output of method [method description].
[def documented]   Output of method [method documented].
[def flags]        A dictionary mapping flag names to flag
                   types, i.e. [const primary], [const alias],
                   or [const inverted].
[def generator]    Output of method [method generator].
[def interactive]  Output of method [method interactive].
[def isbool]       Output of method [method isbool].
[def label]        Output of method [method label].
[def list]         Output of method [method list].
[def ordered]      Output of method [method ordered].
[def presence]     Output of method [method presence].
[def prompt]       Output of method [method prompt].
[def required]     Output of method [method required].
[def threshold]    Output of method [method threshold].
[def type]         Output of method [method type].
[def validator]    Output of method [method validator].
[list_end]
