[list_begin definitions]
[def boolean]		Completable. Accepts a Tcl boolean.
[def identity]	
[def pass]	
[def str]		Infinite.    Accepts all strings.
[def integer]		Infinite.    Accepts a Tcl integer.
[def rdirectory]	Completable. Accepts a readable directory (path).
[def rfile]		Completable. Accepts a readable file (path).
[def rpath]		Completable. Accepts a readable path.
[def rwdirectory]	Completable. Accepts a read/writable directory (path).
[def rwfile]		Completable. Accepts a read/writable file (path).
[def rwpath]		Completable. Accepts a read/writable path.
[list_end]
